window.CAROUSEL_PHOTOS = [
  { src: "assets/images/adam-crystal-barnes-portrait.jpg", alt: "Adam and Crystal Barnes, owners of Southern Spoon" },
  { src: "assets/images/adam-crystal-barnes-portrait-2.jpg", alt: "Adam and Crystal Barnes, owners of Southern Spoon" },
  { src: "assets/images/adam-barnes-solo-portrait.jpg", alt: "Chef Adam Barnes, co-owner of Southern Spoon" },
  { src: "assets/images/crystal-barnes-with-guest.jpg", alt: "Crystal Barnes with a guest at a Southern Spoon event" },
  { src: "assets/images/chef-adam-preparing-grazing-table.jpg", alt: "Chef Adam Barnes preparing a grazing table" },
  { src: "assets/images/chef-adam-serving-food-truck.jpg", alt: "Chef Adam Barnes serving from the Southern Spoon food truck" },
  { src: "assets/images/cocktail-pouring-southern-spoon.jpg", alt: "Cocktail being poured at a Southern Spoon event" },
  { src: "assets/images/bride-groom-eating-appetizers-2.jpg", alt: "Bride and groom enjoying Southern Spoon appetizers at their wedding" },
  { src: "assets/images/appetizer-spread-candles-evening.webp", alt: "Southern Spoon catering photo: Appetizer Spread Candles Evening" },
  { src: "assets/images/appetizer-station-spread.webp", alt: "Southern Spoon appetizer station spread" },
  { src: "assets/images/lemonade-station-outdoor.webp", alt: "Southern Spoon outdoor lemonade station" },
  { src: "assets/images/bar-setup-floral-signage.webp", alt: "Southern Spoon bar setup with floral signage" },
  { src: "assets/images/bar-setup-rustic-pavilion-no-people.webp", alt: "Southern Spoon catering photo: Bar Setup Rustic Pavilion No People" },
  { src: "assets/images/bar-setup-staff-chandelier-venue.webp", alt: "Southern Spoon catering photo: Bar Setup Staff Chandelier Venue" },
  { src: "assets/images/burger-slider-appetizers-tray-closeup.webp", alt: "Close-up of burger slider appetizers on a tray" },
  { src: "assets/images/nashville-hot-fried-chicken-sliders-tray.webp", alt: "Nashville hot fried chicken slider appetizers on a tray" },
  { src: "assets/images/banana-pudding-beignets-dessert.webp", alt: "Banana pudding beignets dessert" },
  { src: "assets/images/buffet-chafing-dishes-setup-wide.webp", alt: "Southern Spoon catering photo: Buffet Chafing Dishes Setup Wide" },
  { src: "assets/images/buffet-rolls-hushpuppies-salad.webp", alt: "Buffet spread of rolls, hushpuppies, and salad at a barn venue" },
  { src: "assets/images/buffet-sides-rice-mac-cheese-overhead.webp", alt: "Southern Spoon catering photo: Buffet Sides Rice Mac Cheese Overhead" },
  { src: "assets/images/buffet-sliders-chips-spread.webp", alt: "Southern Spoon catering photo: Buffet Sliders Chips Spread" },
  { src: "assets/images/buffet-sliders-tray-staff-background.webp", alt: "Southern Spoon catering photo: Buffet Sliders Tray Staff Background" },
  { src: "assets/images/bacon-wrapped-rib-bites-tray.webp", alt: "Bacon-wrapped rib bites appetizer tray" },
  { src: "assets/images/candlelit-barn-tablescape-runway.webp", alt: "Southern Spoon catering photo: Candlelit Barn Tablescape Runway" },
  { src: "assets/images/candy-bar-setup-colorful-display.webp", alt: "Southern Spoon catering photo: Candy Bar Setup Colorful Display" },
  { src: "assets/images/candy-dessert-bar-closeup-colorful.webp", alt: "Southern Spoon catering photo: Candy Dessert Bar Closeup Colorful" },
  { src: "assets/images/caprese-tart-appetizers-tray.webp", alt: "Southern Spoon catering photo: Caprese Tart Appetizers Tray" },
  { src: "assets/images/catering-bar-staff-barn-portrait.webp", alt: "Bar staff portrait at a barn venue" },
  { src: "assets/images/catering-bar-staff-serving-drinks.webp", alt: "Bar staff serving drinks at a catered event" },
  { src: "assets/images/catering-bar-wine-beer-service.webp", alt: "Catering bar setup with wine and beer service" },
  { src: "assets/images/customer-ordering-food-truck-window.jpg", alt: "Customer ordering at the Southern Spoon food truck window" },
  { src: "assets/images/catering-sides-rice-green-beans.webp", alt: "Catering side dishes of wild rice and green beans" },
  { src: "assets/images/catering-team-group-portrait-indoor.webp", alt: "The Southern Spoon catering team" },
  { src: "assets/images/charcuterie-appetizer-spread-wide-2.webp", alt: "Southern Spoon catering photo: Charcuterie Appetizer Spread Wide" },
  { src: "assets/images/charcuterie-board-fruit-cheese-close.webp", alt: "Southern Spoon catering photo: Charcuterie Board Fruit Cheese Close" },
  { src: "assets/images/charcuterie-board-overhead-wood-round.webp", alt: "Southern Spoon catering photo: Charcuterie Board Overhead Wood Round" },
  { src: "assets/images/charcuterie-board-wide-overhead.webp", alt: "Southern Spoon catering photo: Charcuterie Board Wide Overhead" },
  { src: "assets/images/charcuterie-brie-honeycomb-closeup.webp", alt: "Close-up of brie cheese topped with honeycomb" },
  { src: "assets/images/charcuterie-cone-appetizers-board.webp", alt: "Southern Spoon catering photo: Charcuterie Cone Appetizers Board" },
  { src: "assets/images/charcuterie-fruit-board-overhead-2.webp", alt: "Southern Spoon catering photo: Charcuterie Fruit Board Overhead" },
  { src: "assets/images/charcuterie-roulade-appetizer-platter.webp", alt: "Charcuterie and appetizer platter" },
  { src: "assets/images/charcuterie-round-wood-board-vibrant.webp", alt: "Southern Spoon catering photo: Charcuterie Round Wood Board Vibrant" },
  { src: "assets/images/charcuterie-spread-indoor-venue-dim.webp", alt: "Southern Spoon catering photo: Charcuterie Spread Indoor Venue Dim" },
  { src: "assets/images/chef-adam-barnes-with-food-truck.webp", alt: "Chef Adam Barnes standing beside the Southern Spoon food truck" },
  { src: "assets/images/chef-flambe-action-shot.jpg", alt: "Southern Spoon catering photo: Chef Flambe Action Shot" },
  { src: "assets/images/guest-getting-food-grazing-board.webp", alt: "Wedding guest getting food from a Southern Spoon grazing board" },
  { src: "assets/images/chef-portrait-prepping-outdoor.webp", alt: "Southern Spoon catering photo: Chef Portrait Prepping Outdoor" },
  { src: "assets/images/chicken-and-waffle-skewers-plated.webp", alt: "Chicken and waffle skewers plated with syrup" },
  { src: "assets/images/churro-dessert-cups.webp", alt: "Dessert cups topped with churros" },
  { src: "assets/images/coffee-station-catering-detail.webp", alt: "Southern Spoon catering photo: Coffee Station Catering Detail" },
  { src: "assets/images/collard-green-wraps-appetizer.webp", alt: "Collard green wraps arranged on a tray with dipping sauce" },
  { src: "assets/images/contact-banner-customer-truck.jpg", alt: "A smiling customer ordering at the Southern Spoon food truck window" },
  { src: "assets/images/corporate-catering-spread.jpg", alt: "Southern Spoon catering photo: Corporate Catering Spread" },
  { src: "assets/images/cupcake-dessert-table-tiered.webp", alt: "Southern Spoon catering photo: Cupcake Dessert Table Tiered" },
  { src: "assets/images/customer-smiling-with-food-truck-plate.webp", alt: "A happy customer holding a plate of food in front of the Southern Spoon truck" },
  { src: "assets/images/dessert-cups-event-spread-overhead.webp", alt: "Large spread of individual dessert cups at an event" },
  { src: "assets/images/dessert-cups-tray-small-overhead.webp", alt: "Southern Spoon catering photo: Dessert Cups Tray Small Overhead" },
  { src: "assets/images/dessert-mini-trifles-gold-spoons.webp", alt: "Mini dessert trifles with gold spoons and fresh flowers" },
  { src: "assets/images/dessert-tower-cupcakes-display.webp", alt: "Southern Spoon catering photo: Dessert Tower Cupcakes Display" },
  { src: "assets/images/drink-dispensers-labeled-catering.webp", alt: "Southern Spoon catering photo: Drink Dispensers Labeled Catering" },
  { src: "assets/images/fall-dessert-table-pumpkins-candles.webp", alt: "Fall-themed dessert table with pumpkins and candles" },
  { src: "assets/images/flatbread-pork-belly-chalkboard-label.webp", alt: "Southern Spoon catering photo: Flatbread Pork Belly Chalkboard Label" },
  { src: "assets/images/food-truck-blue-hour-guests-walking.webp", alt: "Southern Spoon catering photo: Food Truck Blue Hour Guests Walking" },
  { src: "assets/images/food-truck-dusk-crowd-trees.webp", alt: "Crowd gathered at the Southern Spoon food truck at dusk" },
  { src: "assets/images/food-truck-evening-close-side.webp", alt: "Southern Spoon food truck in evening light" },
  { src: "assets/images/steak-burger-closeup.webp", alt: "Close-up of a Southern Spoon steak burger" },
  { src: "assets/images/food-truck-nashville-skyline-dusk-2.webp", alt: "Southern Spoon food truck near downtown Nashville at dusk" },
  { src: "assets/images/cannolis-on-trays.webp", alt: "Cannolis on trays, a Southern Spoon dessert" },
  { src: "assets/images/food-truck-side-view-daytime.webp", alt: "Southern Spoon catering photo: Food Truck Side View Daytime" },
  { src: "assets/images/food-truck-wide-daytime-grass.webp", alt: "Southern Spoon food truck parked on grass on a sunny day" },
  { src: "assets/images/fried-appetizer-skewers-tray-2.webp", alt: "Southern Spoon catering photo: Fried Appetizer Skewers Tray" },
  { src: "assets/images/sweet-potato-cream-cheese-wontons.webp", alt: "Sweet potato cream cheese wontons appetizer" },
  { src: "assets/images/fried-chicken-bites-skewers-tray.webp", alt: "Southern Spoon catering photo: Fried Chicken Bites Skewers Tray" },
  { src: "assets/images/fried-chicken-bites-with-dip.webp", alt: "Fried chicken bites served with a dipping sauce" },
  { src: "assets/images/charcuterie-board-4.webp", alt: "Charcuterie board" },
  { src: "assets/images/fried-chicken-sliders-closeup.webp", alt: "Close-up of fried chicken slider sandwiches" },
  { src: "assets/images/grazing-spread-colorful-overhead-large.webp", alt: "Southern Spoon catering photo: Grazing Spread Colorful Overhead Large" },
  { src: "assets/images/grazing-table-labeled-ingredients-wide.webp", alt: "Southern Spoon catering photo: Grazing Table Labeled Ingredients Wide" },
  { src: "assets/images/grazing-table-long-wood-board.webp", alt: "Southern Spoon catering photo: Grazing Table Long Wood Board" },
  { src: "assets/images/grazing-table-overhead-1.webp", alt: "Overhead view of a grazing table with fruit, cheese, and charcuterie" },
  { src: "assets/images/customers-buffet-line.webp", alt: "Customers going through a Southern Spoon buffet line" },
  { src: "assets/images/jalapeno-cheddar-cornbread-muffins-appetizer.webp", alt: "Jalapeño cheddar cornbread muffins served as a catering appetizer" },
  { src: "assets/images/grazing-table-tomatoes-charcuterie-wide.webp", alt: "Southern Spoon catering photo: Grazing Table Tomatoes Charcuterie Wide" },
  { src: "assets/images/bride-groom-eating-appetizers-wedding.webp", alt: "Bride and groom enjoying Southern Spoon appetizers at their wedding" },
  { src: "assets/images/guests-buffet-table-formal-event.webp", alt: "Southern Spoon catering photo: Guests Buffet Table Formal Event" },
  { src: "assets/images/guests-candy-bar-table-event.webp", alt: "Southern Spoon catering photo: Guests Candy Bar Table Event" },
  { src: "assets/images/guests-charcuterie-spread-evening-event.webp", alt: "Southern Spoon catering photo: Guests Charcuterie Spread Evening Event" },
  { src: "assets/images/guests-charcuterie-table-formal.webp", alt: "Southern Spoon catering photo: Guests Charcuterie Table Formal" },
  { src: "assets/images/guests-charcuterie-wedding-attire.webp", alt: "Southern Spoon catering photo: Guests Charcuterie Wedding Attire" },
  { src: "assets/images/guests-group-portrait-evening-event.webp", alt: "Southern Spoon catering photo: Guests Group Portrait Evening Event" },
  { src: "assets/images/bride-groom-photobooth-reception.webp", alt: "Bride and groom happy at their wedding reception photobooth" },
  { src: "assets/images/menu-signage-boot-vase-western.webp", alt: "Southern Spoon catering photo: Menu Signage Boot Vase Western" },
  { src: "assets/images/mimosa-juice-station-outdoor.webp", alt: "Southern Spoon catering photo: Mimosa Juice Station Outdoor" },
  { src: "assets/images/brisket-carving-station-buffet.webp", alt: "Brisket carving station at a Southern Spoon catered buffet" },
  { src: "assets/images/outdoor-bar-cart-string-lights.webp", alt: "Southern Spoon catering photo: Outdoor Bar Cart String Lights" },
  { src: "assets/images/outdoor-bar-setup-bottles-no-people.webp", alt: "Southern Spoon catering photo: Outdoor Bar Setup Bottles No People" },
  { src: "assets/images/outdoor-grazing-table-wide.webp", alt: "Outdoor grazing table spread under greenery" },
  { src: "assets/images/passed-appetizer-tray-evening-event.webp", alt: "Southern Spoon catering photo: Passed Appetizer Tray Evening Event" },
  { src: "assets/images/photos-banner-truck-ordering.jpg", alt: "Customers ordering at the Southern Spoon food truck window" },
  { src: "assets/images/plated-brisket-entree-overhead.webp", alt: "Southern Spoon catering photo: Plated Brisket Entree Overhead" },
  { src: "assets/images/plated-entree-overhead-protein-veggies.webp", alt: "Southern Spoon catering photo: Plated Entree Overhead Protein Veggies" },
  { src: "assets/images/plated-fried-chicken-mash-greens-overhead.webp", alt: "Southern Spoon catering photo: Plated Fried Chicken Mash Greens Overhead" },
  { src: "assets/images/plated-salad-overhead-server-hand.webp", alt: "Southern Spoon catering photo: Plated Salad Overhead Server Hand" },
  { src: "assets/images/plated-salad-watermelon-radish.webp", alt: "Southern Spoon catering photo: Plated Salad Watermelon Radish" },
  { src: "assets/images/reception-table-black-linens-gold.webp", alt: "Southern Spoon catering photo: Reception Table Black Linens Gold" },
  { src: "assets/images/reception-table-long-formal-setting.webp", alt: "Long formal wedding reception table setting" },
  { src: "assets/images/reception-table-menu-cards-candles.webp", alt: "Southern Spoon catering photo: Reception Table Menu Cards Candles" },
  { src: "assets/images/reception-table-salad-place-setting.webp", alt: "Salad course plated at a reception table with candles" },
  { src: "assets/images/reception-venue-decor-candlelight.webp", alt: "Southern Spoon catering photo: Reception Venue Decor Candlelight" },
  { src: "assets/images/sweet-potato-cream-cheese-wontons-tray-2.webp", alt: "Sweet potato cream cheese wontons being served on a tray" },
  { src: "assets/images/beef-chimichurri-carving-station.webp", alt: "Beef chimichurri carving station at a Southern Spoon catered buffet" },
  { src: "assets/images/signature-cocktails-bar-sign.webp", alt: "Signature cocktails sign at a Southern Spoon bar setup" },
  { src: "assets/images/customers-lined-up-food-truck.webp", alt: "Customers lined up at the Southern Spoon food truck" },
  { src: "assets/images/stacked-cookie-wedding-cake.webp", alt: "Stacked chocolate chip cookie wedding cake with a rose" },
  { src: "assets/images/steak-sandwich-southern-spoon-shirt.webp", alt: "Steak sandwich held up in front of a Southern Spoon staff shirt" },
  { src: "assets/images/strawberry-dessert-cups-closeup.webp", alt: "Close-up of dessert cups topped with fresh strawberries" },
  { src: "assets/images/tamales-appetizer-tray.webp", alt: "Tray of tamales served with a dipping sauce" },
  { src: "assets/images/tea-station-catering-detail-sign.webp", alt: "Southern Spoon catering photo: Tea Station Catering Detail Sign" },
  { src: "assets/images/tiered-grazing-table-charcuterie.webp", alt: "Tiered grazing table with charcuterie and cheese" },
  { src: "assets/images/team-corporate-event-candy-bar-theme.webp", alt: "The Southern Spoon team at a candy-bar-themed corporate event" },
  { src: "assets/images/wedding-buffet-guests-being-served.webp", alt: "Guests being served at a Southern Spoon wedding buffet" },
  { src: "assets/images/charcuterie-board-5.webp", alt: "Charcuterie board at a Southern Spoon wedding event" },
  { src: "assets/images/wedding-cake-slices-dessert-table.webp", alt: "Wedding cake slices plated on a dessert table" },
  { src: "assets/images/wedding-couple-candid-laughing.webp", alt: "Southern Spoon catering photo: Wedding Couple Candid Laughing" },
  { src: "assets/images/wedding-couple-champagne-toast.webp", alt: "Southern Spoon catering photo: Wedding Couple Champagne Toast" }
];
